### ISSUE TITLE
data_seq_{id}.pkl格式问题

### ISSUE THREAD

**Issue by Xie1ei** [sean-wade/tnt_vectornet_with_tensorrt#1]
请问
“”“
转换前的 pickle 格式如下:
        {
            "trajs"     : [ N * 12], 
            "lane"      : [ M * dict{'lane_id'      : 0, 
                                    'lane_type'     : 'LANE_LINE'
                                    'confidence',   : 0.0
                                    'points_color', : 1
                                    'points_type',  : 1
                                    'points'        : L * 2
                                    }],
            # "tl"      : [ 5 * 2]
        }
”“”
其中，”trajs“中 [N*12]中12维向量的含义是？

**Comment by sean-wade** [comment]
抱歉，最近比较忙忘记回复。
具体含义是我自己的数据中的内容：
[timestamp_0, track_id, type, gx, gy, gz, dx, dy, dz, vx, vy, heading]
你可以参考我的 dev 分支中的代码：
https://github.com/sean-wade/tnt_vectornet_with_tensorrt/blob/dev/dataset/sg_rosbag_process/generate_ego_traj_feature.py
