### ISSUE TITLE
The GPU you used

### ISSUE THREAD

**Issue by 9p15p** [sean-wade/tnt_vectornet_with_tensorrt#2]
Hi，Thanks for your great work.

Could you tell us how many GPUs this project need.

**Comment by sean-wade** [comment]
I use only 1 gpu both in my training & inference

**Comment by Xinchengzelin** [comment]
292ms 是在什么型号的GPU的结果？

**Comment by sean-wade** [comment]
> 292ms 是在什么型号的GPU的结果？

0.292ms，在Nvidia 3090 测试的结果，不包含地图编码时间
