### ISSUE TITLE
Graph structure pytorch code tranfer ONNX

### ISSUE THREAD

**Issue by flyzenr** [sean-wade/tnt_vectornet_with_tensorrt#5]
最近正在做估计预测的部署项目，感谢博主分享这个代码项目，我在将torch转换成ONNX格式时，出现了这个错误，请问博主是否有解决这个问题。

RuntimeError: ONNX export failed on an operator with unrecognized namespace torch_scatter::scatter_max. If you are trying to export a custom operator, make sure you registered it with the right domain and version.

**Comment by sean-wade** [comment]
> 最近正在做估计预测的部署项目，感谢博主分享这个代码项目，我在将torch转换成ONNX格式时，出现了这个错误，请问博主是否有解决这个问题。
> 
> RuntimeError: ONNX export failed on an operator with unrecognized namespace torch_scatter::scatter_max. If you are trying to export a custom operator, make sure you registered it with the right domain and version.

抱歉才看到, scatter_max算子不支持onnx导出, 如果你要导出, 可以参考这个文件:https://github.com/sean-wade/tnt_vectornet_with_tensorrt/blob/dev/assets/export/vectornet_export_v1.py, 但是这里scattermax是一个假的实现, 导出的onnx只能用netron查看结构, 不能实际运行
